### ISSUE TITLE
Option to use `ByteArray` instead of `Array<felt252>`

### ISSUE THREAD

**Issue by MartianGreed** [carbonable-labs/svgenerator#9]
# Description
When we created this tool a while only available option to return strings was to return `Array<felt252>`.

# Additional Information
[ High Difficulty - Rust - Low Priority]

# TODO
Implement an option that will be used like this : 
```
cargo run -- generate path/to/yourfile.svg --type ByteArray
```
Option will default to **`Array<felt252>`**.

With `--type` option specified, program will then return generated cairo with type passed in option.

# Acceptance Criteria
- [ ] Add an option to change cairo base type (used in functions input and output)
- [ ] Program is usable without the option specified (defaulting to `Array<felt252>`)
- [ ] Program is usable with option specified and will fail if type other than `ByteArray` is specified
- [ ] Code decoupling to write cairo program should be decoupled for different type handlers
- [ ] Common code should be then generic

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by IjayAbby** [comment]
Hello @MartianGreed and @Khyati729, I am a Basecamp 9 starknet graduate and I have recently acquired skills in Cairo and Rust language and would love to take up the issue to make use of my skills. Thank you

**Comment by Khyati729** [comment]
> Hello @MartianGreed and @Khyati729, I am a Basecamp 9 starknet graduate and I have recently acquired skills in Cairo and Rust language and would love to take up the issue to make use of my skills. Thank you

Hey @IjayAbby 
could you please go to telegram : https://t.me/carbonableOD
Present yourself and 
explain shortly how you want to tackle the issue

**Comment by TropicalDog17** [comment]
Hi @Khyati729, could I work on this issue?
